spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username : root
    password : 1234
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: trace # Redis ??? ?? ??? ????? ?? (?? ??, ?? ? ? ???? ? ? ??)


---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://instagram-db.ca9ec84cia66.us-east-1.rds.amazonaws.com/mydb
    username: admin
    password: sns54466549!
    driver-class-name: com.mysql.cj.jdbc.Driver


